name: Build Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip ccache bc cpio flex bison git python-is-python3 libc6 libc6-dev tar perl curl lz4

    - name: Download Toolchains (Clang & GCC)
      run: |
        # Download Clang 11
        git clone --depth=1 -b clang-11 https://github.com/rsuplaygrnd/toolchains.git $HOME/clang-11
        
        # Download GCC
        git clone --depth=1 -b gcc https://github.com/blxyzY/toolchain.git $HOME/gcc

    - name: Overwrite and Create build_kernel.sh
      run: |
        cat << 'EOF' > build_kernel.sh
        #!/bin/bash

        export TC=$HOME/clang-11
        export GCC=$HOME/gcc

        # Setup Compiler & Toolchain Path
        export CROSS_COMPILE=$GCC/bin/aarch64-linux-android-
        export CROSS_COMPILE_ARM32=$GCC/bin/arm-linux-androideabi-
        export LD=$TC/bin/ld.lld
        export OBJCOPY=$TC/bin/llvm-objcopy
        export AS=$TC/bin/llvm-as
        export NM=$TC/bin/llvm-nm
        export STRIP=$TC/bin/llvm-strip
        export OBJDUMP=$TC/bin/llvm-objdump
        export READELF=$TC/bin/llvm-readelf
        export CC=$TC/bin/clang
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export ARCH=arm64

        export KCFLAGS=-w
        export CONFIG_SECTION_MISMATCH_WARN_ONLY=y

        # Clean up
        make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y clean && make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y mrproper
        clear

        # Configure & Build
        make -s -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y vendor/a23_open_eur_defconfig
        make -s -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y -j$(nproc)

        # Copy Output
        cp out/arch/arm64/boot/Image $(pwd)/arch/arm64/boot/Image
        EOF
        
        chmod +x build_kernel.sh

    - name: Run Build Script
      run: |
        ./build_kernel.sh

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-a23-Build
        path: |
          arch/arm64/boot/Image
          out/arch/arm64/boot/*.dtb
          out/arch/arm64/boot/*.dtbo
        if-no-files-found: warn
