name: Build Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip ccache bc cpio flex bison git python-is-python3 libc6 libc6-dev tar perl curl lz4

    - name: Download Toolchains (Clang & GCC)
      run: |
        # Download Clang 11
        git clone --depth=1 -b clang-11 https://github.com/rsuplaygrnd/toolchains.git $HOME/clang-11
        
        # Download GCC
        git clone --depth=1 -b gcc https://github.com/blxyzY/toolchain.git $HOME/gcc

    - name: Overwrite and Create build_kernel.sh
      run: |
        chmod +x build_kernel.sh

    - name: Run Build Script
      run: |
        ./build_kernel.sh

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-a23-Build
        path: |
          arch/arm64/boot/Image
          out/arch/arm64/boot/*.dtb
          out/arch/arm64/boot/*.dtbo
        if-no-files-found: warn
